"""Private native-extension typing surface; not part of the public API."""

from __future__ import annotations

class NativeUnsupportedFeatureError(ValueError): ...

NATIVE_SERVICE_API_VERSION: int

class _NativeServiceSymbols:
    def summary(self) -> tuple[int, list[int], bytes]: ...
    def metrics(self) -> tuple[int, int]: ...
    def record(self, id: int) -> tuple[int, str]: ...
    def find(self, kind: int, iri: str) -> int | None: ...
    def range(self, kind: int) -> tuple[int, int]: ...

class _NativeServiceResult:
    def payloads(self, session: NativeSession) -> tuple[tuple[object, ...], tuple[object, ...]]: ...

class NativeSession:
    def service_symbols(self) -> _NativeServiceSymbols: ...
    def service_taxonomy(self, kind: int) -> _NativeServiceResult: ...
    def service_realization(self) -> _NativeServiceResult: ...
    def service_query(
        self, query_ir: bytes | None, kind: int, direct: bool
    ) -> _NativeServiceResult: ...
    def service_named_query(
        self, entity_kind: int, iri: str, kind: int, direct: bool
    ) -> _NativeServiceResult: ...
    def compiler_metadata(self) -> bytes: ...
    def is_inconsistent(self) -> bool: ...
    def class_taxonomy(self) -> bytes: ...
    def object_property_taxonomy(self) -> bytes: ...
    def realization(self) -> bytes: ...
    def query_class_expression(self, query_ir: bytes | None, kind: int, direct: bool) -> bytes: ...
    def entails(self, query_ir: bytes | None) -> bool: ...
    def debug_snapshot(self, realize: bool = False, limit: int = 1_000_000) -> bytes: ...
    def diagnostics(self) -> dict[str, int | float | str | bool]: ...
    def close(self) -> None: ...

def implementation_version() -> str: ...
def ir_version() -> tuple[int, int]: ...
def abi_version() -> str: ...
def self_check() -> bool: ...
def encoded_view_schemas() -> dict[str, int]: ...
def create_session_from_encoded(
    encoded_view: object, workers: int, unsupported: str, *, require_native_pipeline: bool = False
) -> NativeSession: ...
def create_session(ir: bytes, workers: int) -> NativeSession: ...
