"""Private native-extension typing surface; not part of the public API."""

from __future__ import annotations

class NativeSession:
    def is_inconsistent(self) -> bool: ...
    def class_taxonomy(self) -> bytes: ...
    def object_property_taxonomy(self) -> bytes: ...
    def realization(self) -> bytes: ...
    def query_class_expression(self, query_ir: bytes | None, kind: int, direct: bool) -> bytes: ...
    def entails(self, query_ir: bytes | None) -> bool: ...
    def debug_snapshot(self, realize: bool = False, limit: int = 1_000_000) -> bytes: ...
    def diagnostics(self) -> dict[str, int | float | str | bool]: ...
    def close(self) -> None: ...

def implementation_version() -> str: ...
def ir_version() -> tuple[int, int]: ...
def abi_version() -> str: ...
def self_check() -> bool: ...
def encoded_view_schemas() -> dict[str, int]: ...
def create_session_from_encoded(
    encoded_view: object, workers: int, unsupported: str
) -> NativeSession: ...
def create_session(ir: bytes, workers: int) -> NativeSession: ...
